version: "3.8"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env # ← your MONGO_URI, JWT_SECRET, etc.
    ports:
      - "5000:5000"
    restart: unless-stopped

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
