version: "3.8"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./server/.env
    ports:
      - "5001:5000" # Use port 5001 on the host for testing

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:80" # Use port 8081 on the host for testing
